export const span   = (text, className = '') => ({ text, className })
export const green  = (t) => span(t, 'term-green')
export const cyan   = (t) => span(t, 'term-cyan')
export const yellow = (t) => span(t, 'term-yellow')
export const red    = (t) => span(t, 'term-red')
export const purple = (t) => span(t, 'term-purple')
export const muted  = (t) => span(t, 'term-muted')
export const plain  = (t) => span(t)
export const line   = (...spans) => ({ type: 'output', spans })
export const blank  = ()         => ({ type: 'output', spans: [{ text: '' }] })
export const divider= (len = 52) => line(muted('─'.repeat(len)))
